Study_Group_2/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.redirect_view),
    path('home/',include('home.urls')),
    path('main/',include('main.urls')),
    path('api/',include('api.urls'))
]

api/urls.py
from django.urls import path
from api import views
from rest_framework.authtoken.views import obtain_auth_token
app_name = 'api'
urlpatterns = [
    path('get_messages',views.get_messages,name = 'get_messages'),
    path('subjects',views.get_subjects,name = 'subjects'),
    path('register',views.regiter_user,name = 'register'),
    path('login',obtain_auth_token,name = 'login'),
    path('get_id',views.get_user_id,name='get_id'),
    path('get_user_subjects',views.get_user_classes,name='user_classes'),
    path('join_class',views.join_class,name='join_class'),
    path('add_subject',views.add_subject,name='add_subject'),
    path('send_message',views.send_message,name='send_message')
]

main/urls.py
from django.urls import path,include
from . import views
app_name = 'main'
urlpatterns = [
    #path('',views.MainPageView.as_view(),name='main'),
    path('',views.MainPageView.as_view(),name='main'),
    path('add',views.SubjectCreate.as_view(),name='add'),
    path('join',views.SubjectJoin.as_view(),name='join'),
    path('sendmessage',views.send_message,name ="send"),
    path('getmessage',views.get_message,name = 'get')
]

main/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.postgres.fields import ArrayField
from django.conf import settings
# Create your models here.
class Subject(models.Model):
    class Meta:
        app_label = 'main'

    name = models.CharField(
        max_length=200,
        help_text='Enter the name of the Group/Forum',
        validators=[MinLengthValidator(1,"Please enter a Group/forum name")]
    )
    neptun =  models.CharField(
        max_length=10,
        help_text='Enter the subject/forum code',
        validators=[MinLengthValidator(1,"Please Enter a group/forum code")]
    )
    professor = models.CharField(
        max_length=200,
        help_text="Enter the name of the admin if exists"
    )

    def __str__(self) -> str:
        return self.name

class SubjectStudent(models.Model):
    class Meta:
        app_label = 'main'
    student_id = models.IntegerField()
    subject_id = models.CharField(max_length= 10,validators=[MinLengthValidator(1)])

    def __str__(self) -> str:
        return self.subject_id
    

class Message(models.Model):
    class Meta:
        app_label = 'main'
    sender = models.CharField(max_length=50, validators=[MinLengthValidator(1)])
    text = models.TextField()
    N_code = models.CharField(max_length = 10,validators=[MinLengthValidator(1,"Please Enter a subject/forum code")])
    timestamp = models.DateTimeField()

    def __str__(self):
        subject = Subject.objects.get(neptun = self.N_code)
        return subject.name +'_'+ self.sender

main/forms.py
from .models import Subject
from bootstrap_modal_forms.forms import BSModalModelForm

class SubjectModelForm(BSModalModelForm):
    class Meta:
        model = Subject
        fields = ['name', 'neptun', 'professor']

main/views.py
from datetime import datetime
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render
from .forms import SubjectModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from bootstrap_modal_forms.generic import BSModalCreateView
import json
from django.http import HttpResponseRedirect


from django.views import View
from .models import Subject, SubjectStudent,Message
# Create your views here.
class MainPageView(LoginRequiredMixin,View):
    login_url = 'login'
    def get(self,request):
        student = request.user
        subject_ids = SubjectStudent.objects.filter(student_id = student.id).only('subject_id')
        subjects = [Subject.objects.get(neptun = id)for id in subject_ids]
        ctx = {'user':student,'subjects':subjects}
        return render(request,'main/main.html',ctx)

class SubjectCreate(LoginRequiredMixin,BSModalCreateView):
    template_name = 'main/subject_form.html'
    form_class = SubjectModelForm
    success_message = 'Success: Subject was added'
    success_url = reverse_lazy('main:main')

    def form_valid(self,form):
        if self.request.is_ajax():
            obj = form.save(commit=False)
            try:
                old = Subject.objects.get(neptun = obj.neptun)
                print(old.name)
                return HttpResponseRedirect(self.success_url)
            except:
                student_id = self.request.user.id
                subject_id = obj.neptun
                subject_student = SubjectStudent(student_id = student_id,subject_id = subject_id)
                print(subject_student.subject_id)
                obj.save()
                subject_student.save()
                return HttpResponseRedirect(self.success_url)
        return HttpResponseRedirect(self.success_url)
        
    

class SubjectJoin(LoginRequiredMixin,View):
    template_name = 'main/join-class.html'
    success_url = reverse_lazy('main:main')
    
    def get(self,request):
        subjects = Subject.objects.all()
        ctx = {'subjects':subjects}
        return render(request,self.template_name,ctx)

    def post(self,request):
        subject_name = request.POST.get('join')
        subject = Subject.objects.get(name= subject_name)
        student = self.request.user
        joined = SubjectStudent.objects.filter(student_id = student.id).filter(subject_id = subject.neptun).count()
        if joined > 0:
            messages.info(request,'Already Enrolled')
        else:
            subject_student = SubjectStudent(student_id = student.id , subject_id = subject.neptun)
            subject_student.save()
            messages.success(request,subject.name+' Joined')
        return HttpResponseRedirect(self.success_url)
    

def send_message(request):
    if request.method == 'POST':
        sender = request.POST['sender']
        message = request.POST['message']
        timestamp = datetime.now()
        subject = request.POST['subject']
        n_code = Subject.objects.get(name = subject)
        message_obj = Message(sender = sender,text = message.strip(),N_code = n_code.neptun ,timestamp = timestamp)
        message_obj.save()
        return HttpResponse('Success')
    return HttpResponse("Dikkat")

def get_message(request):
    if request.method == 'GET':
        subject = Subject.objects.get(name = request.GET['subject'] )
        l = Message.objects.filter(N_code = subject.neptun).order_by('timestamp')
        print(len(l))
        message_list = [{'sender':message.sender,'text':message.text,'datetime':''.join(str(message.timestamp).split('.')[:-1])} for message in l ]
        message_list = json.dumps(message_list,indent=2)
        return HttpResponse(message_list)
        

main/templates/main/join-class.html
<form action="" method="post">
    {% csrf_token %}
    <div class="modal-header" style="background-color: #f3754c">
        <h4 class="modal-title mt-2" id="addSubjectLabel">Join a Subject</h4>
        <input type="button" class="close" data-dismiss="modal" value="X" />
    </div>
    <div class="modal-body mt-1">
        <div class="form-outline">
            <input
            id="searchQuery"
            type="search"
            class="form-control"
            placeholder="Search for a Subject/Forum"
            aria-label="Search"
            onkeyup="filter()"
            />
        </div>
        <div class="overflow-auto mt-1">
            <div  class = "list-group" id="list-tab" role="tablist">
                {% for subject in subjects %}
                <a
                class="list-group-item list-group-item-action"
                id="list-subject-list"

                data-toggle="list"
                onclick="getSubjectName(this.innerText)"
                role="tab"
                style="
                    border-bottom: 1px;
                    border-bottom-style: solid;
                    border-bottom-color: black;
                "
                >
                {{ subject.name }}
                </a>
                {% endfor %}

            </div>
        
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" class="btn btn-primary" value="Join" style="margin-bottom: 5px;"/>
        <input
            type="button"
            class="btn btn-default"
            data-dismiss="modal"
            value="Cancel"
        />
        <input type="hidden" id="joinButton" >
        <script>
            function getSubjectName(subject)
            {
                document.getElementById('joinButton').setAttribute('value',subject)
                document.getElementById('joinButton').setAttribute('name','join')
            }
        </script>
    </div> 
</form>
<script>
    function filter(){
        var input,filter,ul,li,a,i,txtValue;
        input = document.getElementById('searchQuery');
        filter = input.value.toUpperCase();
        ul = document.getElementById('list-tab');
        li = ul.getElementsByTagName('a')

        for (i = 0;i<li.length; i++)
        {
            a = li[i]
            txtValue = a.textContent || a.innerText;
            if(txtValue.toUpperCase().indexOf(filter) > -1)
            {
                li[i].style.display = "";
            }
            else{
                li[i].style.display = "none";
            }
        }
    }
</script>
<script>jQuery("a.list-group-item").click(function (e) {
    jQuery(this).addClass('active').siblings().removeClass('active');
});
</script>

 

main/templates/main/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!--Metadata-->
    <meta charset="utf-8">
    <title>{{user.username }} | Master Minds</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo_size_invert.jpg' %}" alt = 'logo'/>
  
    <!--CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'styles/styles2.css'%}">
    <!--Modal code-->
    <div class="modal fade mt-5" tabindex="-1" role="dialog" id="modal" style="opacity: 1;">
        <div class="modal-dialog" role="dialog">
          <div class="modal-content">
          </div>
        </div>
      </div>
</head>

<body>
  <div class="container app">
    <div class="row app-one">
        <div class="col-sm-4 side">
            <div class="side-one">
                <div class="row heading">
                  <nav class="navbar navbar-light ">
                    <h3 class = "navbar-brand mb-10 " style="margin-left: 5px; font-size: 1.5rem;">{{user.username}}</h3>
                  </nav>
                </div>

                <div class="row searchBox">
                    <div class="col-sm-12 searchBox-inner">
                    <div class="form-group has-feedback">
                        <input id="searchText" type="text" class="form-control" name="searchText" placeholder="Search">
                        <span class="glyphicon glyphicon-search form-control-feedback"></span>
                    </div>
                    </div>
                </div>
                
                <div class="row sideBar overflow">
                    {%for subject in subjects %}
                    <div class="row sideBar-body" onclick="chatClicked(this.innerText)">
                      <div class="col-sm-9 col-xs-9 sideBar-main">
                          <div class="row">
                            <div class="col-sm-8 col-xs-8 sideBar-name">
                              <span class="name-meta">{{subject.name}}
                              </span>
                            </div>
                          </div>
                      </div>
                    </div>
                    {%endfor%}
                </div>

                <div class="card footer">
                  <div class="card-body">
                    <button class="btn primary " style="background-color: rgba(243, 117, 76, 0.65); margin: 2px;"data-toggle = 'tooltip' title = 'Join a Class/Forum' id = "join-subject" >Join Class</button>
                    <button class="btn primary" style="background-color: rgba(243, 117, 76, 0.65); margin: 2px;" id="add-subject" data-toggle = 'tooltip' title="Add a subject/forum">Add Class</button>
                    <button class="btn primary" style="background-color: rgba(243, 117, 76, 0.65); margin: 2px;">
                        <a href="{%url 'home' %}">Logout</a>
                    </button>
                  </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8 conversation" id="con-box">
        <div class="row heading">
          <div class="col-sm-8 col-xs-7 heading-name">
            <h2 class="heading-name-meta" id="chat-heading">
            </h2>
            
          </div>
        </div>
        <div class="row message" id="conversation">

        </div>
        </div>
  </div>
</body>
  <!--JS and JQuery imports-->
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script type="text/javascript" src="{% static 'js/main_js.js' %}"></script>
  <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js'%}"></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <script type="text/javascript">
      var user = "{{user.username|safe}}"
      set_user(user)
      var token = '{{csrf_token}}'
      set_token(token)
  </script>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#add-subject").modalForm({
        formURL: "{% url 'main:add' %}"
        });
    });
  </script>
  <script type="text/javascript">
          $(document).ready(function() {
          
          $("#join-subject").modalForm({
              formURL: "{% url 'main:join' %}"
          });
      
      });
  </script>
</html>

main/templates/main/subject_form.html
{% load crispy_forms_tags %} 

<form  method="post" class="form" role="form" action="">
    {% csrf_token %}
    {{ subject_form|crispy }}  
    <div class="modal-header"style="background-color:#F3754C;">
        <h4 class="modal-title mt-2" id="addSubjectLabel">Add a Subject</h4>
        <input type="button" class="close" data-dismiss="modal" value="X"/>
    </div>
    <div class="modal-body mt-5">
    {{ form.non_field_errors }}
        <div class="form-group">
        {% for field in form %}
            <div class="form-group">
            {% if field.errors %}
                <ul class="form-errors">
                {% for error in field.errors %}
                    <li>
                        <span class="fa fa-exclamation-triangle"></span>
                        <strong>{{ error|escape }}</strong>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
                {% if field.help_text %}
                <div class="form-helptext">
                {{ field.help_text }}
                </div>
                {% endif %}
                {{ field.label_tag }} : {{ field }}        
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel"/>
        <input type="submit" class="btn btn-primary" value="Save" style="margin-bottom: 5px;"/>
    </div>
</form>